[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor --chip esp32 --baud 460800"

[build]
target = "xtensa-esp32-none-elf"
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

[unstable]
build-std = ["core", "alloc"]
