[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor --chip esp32 --baud 460800"

[env] # TODO choose per profile (option 'dotenvy')
ESP_LOG = "debug"
# ESP_LOG = "info"

[build]
target = "xtensa-esp32-none-elf"
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

[unstable]
build-std = ["core", "alloc"]
